export const SAVE_COURSE_REQUEST = "SAVE_COURSE_REQUEST";
export const FETCH_COURSE_REQUEST = "FETCH_COURSE_REQUEST";
export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAILURE = "COURSE_FAILURE";
